name: ollama/SCA Scout

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'The Docker image to scan'
        required: true
        default: 'ollama/ollama'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull the image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ github.event.inputs.docker_image }}
          exit-code: false
          sarif-file: sca_scout.sarif
          output: ollama.spdx.json
          format: spdx
          max-locations: 1000  # Limit related locations to meet GitHub's threshold

      - name: Upload ollama file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama.spdx.json
          path: ollama.spdx.json

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca_scout.sarif
          path: sca_scout.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/SCA

      - name: Ollama upload
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
